#!/bin/sh

set -e
script/bootstrap --local

#check for auth flag
if [ $* -a $1 == "--auth" ]; then
  #server with auth
  echo "Spinning up the server with authentication..."
  bundle exec jekyll-auth
else
  #server sans auth
  echo "Spinning up the server sans authentication..."
  echo "If you want authentication, just add --auth to the script/server command"
  bundle exec jekyll serve -w --config _config.yml,_config.dev.yml
fi

#kill _site folder
echo "cleaning up..."
rm -Rf _site
